apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: forum-app
type: Opaque
stringData:
  PG_DB: forum
  PG_USER: postgres
  PG_PASSWORD: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: forum-app
type: Opaque
stringData:
  SECRET_KEY: your-secret-key