apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ${DOCKER_REGISTRY}/pyforum:${TAG}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: static-files
          emptyDir: {}
      initContainers:
        - name: init-db
          image: ${DOCKER_REGISTRY}/pyforum:${TAG}
          command: ['python', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets