apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config 
data:
  DEBUG: "0"
  ENVIRONMENT: "production"
  ALLOWED_HOSTS: "www.yourdomain.com"
  DJANGO_SETTINGS_MODULE: "forum-sandbox.settings.production"
  STATIC_URL: "https://www.yourdomain.com/static/"
  MEDIA_URL: "https://www.yourdomain.com/media/"
  CSRF_TRUSTED_ORIGINS: "https://www.yourdomain.com"
