apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployments/web-deployment.yml
- deployments/postgres-deployment.yml
- services/web-service.yml
- services/postgres-service.yml
- volumes/postgres-pv.yml
- volumes/postgres-pvc.yml

configMapGenerator:
- files:
  - configmaps/app-config.yml
  name: app-config
- files:
  - configmaps/nginx-config.yml
  name: nginx-config
      
labels:
- includeSelectors: true
  pairs:
    app: web-app
    component: backend
