name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 -U testuser && break
          echo "Waiting for PostgreSQL..."
          sleep 3
        done

    - name: Run Migrations
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}  # Reference the GitHub Secret
        DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
        CORS_ORIGIN_WHITELIST: http://localhost:8000,http://localhost:3000
        PG_DB: testdb
        PG_USER: testuser
        PG_PASSWORD: testpassword
        DB_HOST: localhost
        DB_PORT: 5432
        DB_PORT_OUT: 5432
        EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
        EMAIL_HOST: someuser@gmail.com
        EMAIL_PORT: 587
        EMAIL_USE_TLS: 1
        EMAIL_HOST_USER: test@test.com
        EMAIL_HOST_PASSWORD: test-password
      run: |
        source venv/bin/activate
        python manage.py migrate

    - name: Collect Static Files
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput

    - name: Run Django Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}  # Reference the GitHub Secret
        DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
        CORS_ORIGIN_WHITELIST: http://localhost:8000,http://localhost:3000
        PG_DB: testdb
        PG_USER: testuser
        PG_PASSWORD: testpassword
        DB_HOST: localhost
        DB_PORT: 5432
        DB_PORT_OUT: 5432
        EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
        EMAIL_HOST: someuser@gmail.com
        EMAIL_PORT: 587
        EMAIL_USE_TLS: 1
        EMAIL_HOST_USER: test@test.com
        EMAIL_HOST_PASSWORD: test-password
      run: |
        source venv/bin/activate
        python manage.py test

    - name: List installed packages
      run: |
        source venv/bin/activate
        pip list

    - name: Check Python Version
      run: |
        which python
        python --version